### ISSUE TITLE
SeString payload exception causing full text search to fail.

### ISSUE THREAD

**Issue by wrath16** [NotNite/Alpha#9]
I was wondering why full text search wasn't working on some sheets so I did some digging and apparently there's a couple of cells in the data sheets which are throwing exceptions when it tries to parse the SeString. 

The problem cells in question are on `CustomTalkDefineClient` row 4, column 0, and `QuestDefineClient` row 136, column 0.

Here is the stack trace it spits out: 

```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Lumina.Text.Payloads.BasePayload..ctor(Stream stream)
   at Lumina.Text.SeString.BuildPayloads()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Alpha.Utils.UiUtils.XmlRepr(StringBuilder sb, SeString s) in ..\Alpha\Alpha\Utils\UiUtils.cs:line 68
   at Alpha.Utils.UiUtils.DisplaySeString(SeString s) in ..\Alpha\Alpha\Utils\UiUtils.cs:line 84
   at Alpha.Modules.Excel.ExcelModule.DisplayObject(Object obj) in ..\Alpha\Alpha\Modules\Excel\ExcelModule.cs:line 355
   at Alpha.Windows.ExcelWindow.<>c__DisplayClass31_1.<ResolveSidebarFilter>b__1() in ..\Alpha\Alpha\Windows\ExcelWindow.cs:line 605
```

**Comment by NotNite** [comment]
I'm currently working on a full rewrite of Alpha at the moment, so it's unlikely I'll fix it soon, but I'll make sure this is accounted for there.
